"use client"

import "./globals.css"
import { theme } from "../theme/theme"
import { ThemeProvider, CssBaseline } from "@mui/material"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Movies app</title>
        <meta name="my movies app" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <body>{children}</body>
      </ThemeProvider>
    </html>
  );
}