"use client"

import "./globals.css"
import { ThemeProvider, CssBaseline } from "@mui/material"
import { theme } from "@/theme/theme"
import { store } from "@/store/store"
import { Provider } from "react-redux";

import ResponsiveAppBar from "@/components/appBar"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Movies app</title>
        <meta name="my movies app" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <body>
          <Provider store={store}>
            <ResponsiveAppBar />
            {children}
          </Provider>
        </body>
      </ThemeProvider>
    </html>
  );
}